ewm-main-server
lap-lik/explore-with-me pull request #2
Opened 2024-05-26 18:23 UTC by lap-lik

2024-07-06 01:27 UTC, lap-lik commented
Добрый день.

Дипломный проект Этап - 2:

Слегка сумбурно написан проект, часть кода писал после перерыва в месяц, местами код изменил и в сервисе статистики из 1 этапа.

2024-07-07 07:51 UTC, Fleaman777 requested changes

2024-07-07 07:51 UTC, Fleaman777 commented on docker-compose.yml
>    stats-server:
можно было бы переимновать `stats-server` в `ewm-stats-server` для консистентности с другими именами контейнеров.

2024-07-07 07:51 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:14-alpine
хороший выбор образа `postgres:14-alpine` для меньшего размера и быстрой загрузки.

2024-07-07 07:51 UTC, Fleaman777 commented on main-server/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +                        .build());
доставание compilation можно было бы вынести в отдельный общий метод, что бы уменьшить дублирование, 
возможно как-то объекденить с checkExistsCompilationById

2024-07-07 07:51 UTC, Fleaman777 commented on main-server/src/main/java/ru/practicum/event/service/EventService.java
> +    EventDtoOut getByPublic(long eventId, HttpServletRequest request);
по хорошему, в слоый сервис не должен передаваться объект HttpServletRequest request, так как в сервисе уже идет логика независимая от контроллера, а реквест - объект который по большей части относится именно к контроллеру, 
если нам нужны какие-то отдельные поля в методе в сервисе, то их можно передать явно

аналогично с др методами

2024-07-07 07:51 UTC, Fleaman777 commented on main-server/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (!Objects.equals(event.getState(), EventState.PUBLISHED)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, и выглядит чуть очевидней

2024-07-07 07:51 UTC, Fleaman777 commented on main-server/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        if (Objects.isNull(ids) || ids.isEmpty()) {
по большей части вкусовщина, но по мне ids == null такое сравнение чуть привычней

2024-07-07 07:51 UTC, Fleaman777 commented on main-server/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        if (!isExist) {
почему бы сразу не сделать if(!dao.existsById(userId)) ...
условие не сложное, кода не много

2024-07-07 07:51 UTC, Fleaman777 commented on stats-server/stats-client/src/main/java/ru/practicum/exception/StatsClientErrorHandler.java
> +                .errors(convertStackTraceToStringList(exception))
а нужен ли клиенту наш стректрейс, 
его можно оставиь в логах, в которых, если будет необходимо, мы сами проверим, что пошло не так 
а клиенту долждно быть достататочно, код ошибки, причина, ну и время можно добавить

2024-07-07 07:59 UTC, lap-lik commented on stats-server/stats-client/src/main/java/ru/practicum/exception/StatsClientErrorHandler.java
> +                .errors(convertStackTraceToStringList(exception))
Так по ТЗ из Swagger
<img width="399" alt="image" src="https://github.com/lap-lik/java-explore-with-me/assets/70767412/eaeb507a-fe84-46a1-a252-43d1f507550d">

2024-07-07 08:00 UTC, lap-lik commented on main-server/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        if (!isExist) {
Поправил.

2024-07-07 08:02 UTC, lap-lik commented on main-server/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        if (Objects.isNull(ids) || ids.isEmpty()) {
Как-то для себя принял использовать для проверки методы класса `Objects.`, после того как несколько раз на NullPointerException попал.
Пока мне так удобнее.

2024-07-07 08:05 UTC, lap-lik commented on main-server/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (!Objects.equals(event.getState(), EventState.PUBLISHED)) {
Как-то для себя принял использовать для проверки методы класса Objects., после того как несколько раз на NullPointerException попал.
Пока мне так удобнее.

2024-07-07 08:27 UTC, lap-lik commented on main-server/src/main/java/ru/practicum/event/service/EventService.java
> +    EventDtoOut getByPublic(long eventId, HttpServletRequest request);
Исправил, в сервисный слой уходят параметры String ip, String uri.

2024-07-07 08:31 UTC, lap-lik commented on main-server/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +                        .build());
Исправил, вынес в отдельный приватный метод.

2024-07-07 08:33 UTC, lap-lik commented on docker-compose.yml
>    stats-server:
Долго настраивал взаимодействие docker-compose.yml и прочих объектов проекта, боюсь что-нибудь поломать.
Прошу принять в таком варианте.

2024-07-08 06:57 UTC, Fleaman777 commented on main-server/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        if (Objects.isNull(ids) || ids.isEmpty()) {
вообще еще можно подтянуть библиотеку apachф которая с коллекциями рабоатает, там есть хорошие методы которые сразу проверяют и на null и на пустоту,  даже есть методы наоборот notEmpty..

что довольно часто применяется

2024-07-08 06:58 UTC, Fleaman777 commented on stats-server/stats-client/src/main/java/ru/practicum/exception/StatsClientErrorHandler.java
> +                .errors(convertStackTraceToStringList(exception))
а все, вопрос снят) 

но по мне, немного странно

2024-07-08 06:58 UTC, Fleaman777 approved these changes

2024-07-08 08:49 UTC, merged